version: '3'

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: hamdydb
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - "./DB:/docker-entrypoint-initdb.d"




